<?xml version="1.0" encoding="UTF-8" standalone="yes"?><ns2:test-suite xmlns:ns2="urn:model.allure.qatools.yandex.ru" start="1399987040975" stop="1399987061240"><name>my.company.ManyInfoTest</name><description type="text">Testsuite has testcases with many steps
    and
many lines in description</description><test-cases><test-case start="1399987041306" stop="1399987041542" status="failed"><name>attachmentsTest</name><description type="text">Single-line description</description><failure><message>AssertionError: This test should be failed</message><stack-trace>java.lang.AssertionError: This test should be failed
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at my.company.steps.CommonSteps.makeThisTestFailed(CommonSteps.java:36)
	at my.company.ManyInfoTest.attachmentsTest(ManyInfoTest.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:722)
</stack-trace></failure><steps><step start="1399987041535" stop="1399987041541" status="failed"><name>makeThisTestFailed</name><title>Make this test failed</title><attachments><attachment title="TXT Attachment" source="b331a5914c7e78df1aaaad982bbe6b0c657aaa0391d15e105af376daf6b439cc-attachment.txt" type="txt"/></attachments></step></steps><attachments><attachment title="JSON Attachment" source="c5a63c63adb9adda21cbdd82dbd649ac4cb661acde06e27add40f32b60886acf-attachment.json" type="json"/><attachment title="XML Attachment" source="6deda11b86bff62c7252fc47a68ed8d632c4dff891f3641e38f7259bc419c9bf-attachment.xml" type="xml"/><attachment title="JPG Attachment" source="ad720ddaaa92f973fa78080750eeeca731d32de1cebb6d105c0bce46f7f8c548-attachment.jpg" type="jpg"/></attachments><labels><label name="story" value="OtherScreenshot"/><label name="feature" value="Screenshot"/><label name="severity" value="critical"/></labels></test-case><test-case start="1399987041306" stop="1399987041493" status="failed"><name>longAssertionTest</name><title>Test with long assertion text</title><failure><message>AssertionError: 
Expected: "{\n\"name\": \"test\",\n\"value\": \"ok value\"\n}"
     but: was "{\n\"name\": \"test\",\n\"value\": \"bad value\"\n}"</message><stack-trace>java.lang.AssertionError: 
Expected: "{\n\"name\": \"test\",\n\"value\": \"ok value\"\n}"
     but: was "{\n\"name\": \"test\",\n\"value\": \"bad value\"\n}"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert.assertThat(Assert.java:832)
	at my.company.ManyInfoTest.longAssertionTest(ManyInfoTest.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:722)
</stack-trace></failure><steps/><attachments><attachment title="System Environment" source="8c9214b3b320b09447609fc1e6eac0e4decf97ef4b9cf9e0da2fa24d9d616500-attachment.txt" type="txt"/></attachments><labels><label name="severity" value="normal"/></labels><parameters><parameter name="PATH" value="/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/git/bin:/usr/local/Cellar/maven/3.0.5/libexec/bin:/Library/Java/JavaVirtualMachines/jdk1.7.0_21.jdk/Contents/Home/bin" kind="environment-variable"/><parameter name="BASEDIR" value="/Users/charlie/IdeaProjects/allure-junit-variant" kind="environment-variable"/><parameter name="OS_NAME" value="Mac OS X" kind="environment-variable"/><parameter name="OS_VERSION" value="10.9.1" kind="environment-variable"/><parameter name="JAVA_VERSION" value="1.7.0_21" kind="environment-variable"/></parameters></test-case><test-case start="1399987041306" stop="1399987041368" status="broken"><name>lotOfStepsTest</name><description type="text">I have many steps 

    Parent Step 
    Last 
    MakeThisTestBroken</description><failure><message>FileNotFoundException: No file found.</message><stack-trace>java.io.FileNotFoundException: No file found.
	at my.company.steps.CommonSteps.makeThisTestBroken(CommonSteps.java:30)
	at my.company.ManyInfoTest.lotOfStepsTest(ManyInfoTest.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:722)
</stack-trace></failure><steps><step start="1399987041356" stop="1399987041361" status="passed"><name>parentStep</name><title>Parent step</title><steps><step start="1399987041356" stop="1399987041360" status="passed"><name>step</name><title>"First nested" step</title></step><step start="1399987041361" stop="1399987041361" status="passed"><name>step</name><title>"Second nested" step</title></step><step start="1399987041361" stop="1399987041361" status="passed"><name>step</name><title>"Third nested" step</title></step></steps></step><step start="1399987041361" stop="1399987041361" status="passed"><name>step</name><title>"Last" step</title></step><step start="1399987041361" stop="1399987041368" status="broken"><name>makeThisTestBroken</name><title>Make this test broken</title></step></steps><attachments/><labels><label name="severity" value="blocker"/></labels></test-case></test-cases><labels/></ns2:test-suite>